[ko]
  languageName = "Korean (한국어)"
  contentDir = "content/ko"
  weight = 10
  [ko.params]
    languageISO = "KO"
    languageTag = "ko-KR"
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
